wallpaper {
    monitor = DP-2
    path = /home/hapax/.config/hypr/wallpaper-rnd-primary.png
}

wallpaper {
    monitor = DP-1
    path = /home/hapax/.config/hypr/wallpaper-rnd-secondary.png
}

splash = false
